### ISSUE TITLE
Missing support for Angular 10

### ISSUE THREAD

**Issue by mroohian** [bertrandg/angular-split#233] opened 2020-07-03 14:02 UTC
**Describe the bug**
Execution of apps fails due to errors. The error happens because of the changes in module `forRoot` return type:

`static forRoot(): ModuleWithProviders<T>`

https://angular.io/api/core/ModuleWithProviders

**To Reproduce**
Install angular-split into an Angular 10 project and run

**Comment by nomeaning777** [comment] 2020-07-03 14:48
This issue will be fixed by the changes in #204, but it is not reviewed for a long time.

**Comment by beeman** [comment] 2020-07-12 01:05
Because the maintainer of `angular-split` clearly lost interest in maintaining it, and does seem to be interested in adding collaborators, I decided to fork this awesome library.

The fork is called `ngx-split`. Check the [homepage](https://beeman.github.io/ngx-split/), [npm package](https://npm.im/ngx-split/) and [repo](https://github.com/beeman/ngx-split/) . 

@mroohian this issue should be fixed in `ngx-split`.

**Comment by beeman** [comment] 2020-07-23 17:14
@mroohian Thanks to @bertrandg I've been given permissions to maintain this library. I just released a new beta, `angular-split@4.0.0-beta.0`, can you verify if this works with Angular 10?

**Comment by Rajdeep97** [comment] 2020-07-23 19:45
Hi @beeman,

Before today's commit, I tried using this library in my Angular 10 project and it worked well. I will install the beta also and let you know.

**Comment by beeman** [comment] 2020-07-23 23:16
Support for Angular 10 is now verified using [this repo](https://github.com/beeman/split-sandbox-v10).

If you find any issues with v10, please open a new issue with a reproduction. 🙏

**Closed by beeman** 2020-07-23 23:16 UTC
Labels: bug
