### ISSUE TITLE
doesn't recognize given [size] values on initializing

### ISSUE THREAD

**Issue by Shukarity** [bertrandg/angular-split#87] opened 2018-02-09 11:43 UTC
Take this site example for instance:

`<split direction="horizontal">
    <split-area [size]="40">
        <split direction="vertical">
            <split-area>
                <p>Lorem ipsum dolor sit amet...</p>
            </split-area>
            <split-area>
                <p>Sed ut perspiciatis unde omnis iste natus erro...</p>
            </split-area>
            <split-area>
                <p>Lorem ipsum dolor sit amet...</p>
            </split-area>
        </split>
    </split-area>
    <split-area [size]="60">
        <split direction="vertical">
            <split-area [size]="25">
                <p>Lorem ipsum dolor sit amet...</p>
            </split-area>
            <split-area [size]="75">
                <p>Sed ut perspiciatis unde omnis iste natus erro...</p>
            </split-area>
        </split>
    </split-area>
</split>`

What I get is a collapsed view of all panes, except 1 of them which spreads on the rest of the screen (entire)

But when I use routerLink to navigate elsewhere and then use routerLink to navigate back, I get the expected view of the given sizes.

I get this bad behavior on refresh and on lazyloading

Using this inside a mat-nav-container if thats useful

**Comment by MattSykes78** [comment] 2018-02-11 23:54
Same behviour for me:

`<split direction="vertical">
	<split-area [visible]="!hideTopPanel" [order]="1">
		<div class="upperpane">
   		</div>
	</split-area>
	<split-area [visible]="hideLeftPanel === false || hideRightPanel === false" [order]="2">
		<div class="lowerpane">
			<split direction="horizontal">
				<split-area [size]="60" [visible]="!hideLeftPanel" [order]="3">
					<div class="leftpane">		
					</div>
				</split-area>
				<split-area [size]="40" [visible]="!hideRightPanel" [order]="4">
					<div class="rightpane">
					</div>
				</split-area>
			</split>
		</div>
	</split-area>
</split>`

package.json:
`"dependencies": {
    "@angular/animations": "^5.2.2",
    "@angular/cdk": "^5.1.0",
    "@angular/common": "^5.2.2",
    "@angular/compiler": "^5.2.2",
    "@angular/core": "^5.2.2",
    "@angular/forms": "^5.2.2",
    "@angular/http": "^5.2.2",
    "@angular/material": "^5.1.0",
    "@angular/platform-browser": "^5.2.2",
    "@angular/platform-browser-dynamic": "^5.2.2",
    "@angular/router": "^5.2.2",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.7",
    "angular-split": "^1.0.0-rc.3",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "lodash": "^4.17.4",
    "moment": "^2.20.0",
    "ng2-pagination": "^2.0.2",
    "papaparse": "^4.3.6",
    "rxjs": "^5.5.2",
    "xlsx": "^0.11.14",
    "zone.js": "^0.8.14"
  },`

Is there an issue with having nested splits where the horizontal split is the container?  I noticed in your nested example it's the vertical split as the container

**Comment by bertrandg** [comment] 2018-02-12 16:01
Hi,

@MattSykes78 No I don't think there's issue about that, check this demo:
https://stackblitz.com/edit/angular-zatkqg?file=app%2Fapp.component.html

@Shukarity 
It seems related to the integration inside material layout, please provide a stackblitz showing your issue.

**Comment by Shukarity** [comment] 2018-02-12 22:35
Ok, made one. Man I don't know what's up. It works beautifully here...
https://stackblitz.com/edit/angular-split-material-layout

I have not tested with lazyloading implementation yet, it could be that

**Comment by Shukarity** [comment] 2018-02-12 22:57
I have tested it in my own project without the lazyLoading. It all works perfect. Lazy loading is definately the issue

**Comment by MattSykes78** [comment] 2018-02-12 23:08
I'm also lazy loading the component with angular-split

**Comment by MattSykes78** [comment] 2018-02-12 23:59
@bertrandg thanks for the link, I'll try and see if I can get to the root of this issue and get back to you, I've removed lazy loading like @Shukarity has, however I still see the issue so maybe it's a combination of things for me.  I'll upload a demo if I think I can isolate it enough.

**Comment by MattSykes78** [comment] 2018-02-13 07:10
An update from my end:
* Non-nested split in lazy loaded component picks up the sizing on initialization just fine for me.
* I could not get a nested split in lazy loaded component to initialize correctly, however I noticed that if you hide and show the component manually (via a button that changes the visible bound value) it has the correct size, it just hadn't initialized on component load.

Due to time constraints I have simply worked around the issue by coding the hide and show after the child components in the splits have loaded, eg:
`this.hideTopPanel = true;
this.hideLeftPanel = true;
this.ref.detectChanges();
this.hideTopPanel = false;
this.hideLeftPanel = false;
this.ref.detectChanges();`

It now performs as I want, even if the solution is not 100% clean.  I was unable to reproduce the issue in stackblitz and there are many sub components in my application creating a lot of variables making it hard to determine the exact cause, without spending a lot of time I don't currently have.

From what I have observed in the browser development window, the split area element style values of flex and size did not seem to match the ng size bound value on initial load, as to whether that means anything I'm not sure, just thought I'd pass that along.

**Comment by magnusbakken** [comment] 2018-03-01 14:31
I have the exact same issue. The top panel in a vertical split starts out collapsed. I did something similar to the workaround suggested by @MattSykes78, which works, but it's not pretty.

**Comment by mfor** [comment] 2018-05-31 15:46
Same here.  Simple vertical split doesn't recognize the size=50, or no size at all. Starts off with one collapsed and the second expanded to full.   
Is the workaround to use AfterViewInit, and change variables controlling the visible Directive? My attempts still result in a collapsed split-area

**Comment by dpatel44725** [comment] 2018-11-21 18:19
I have the same issue, but the only thing in my project is i am using this as-split inside **MatTabModule**

then it doesn't recognize the given size. 

```
<mat-tab-group>
  <mat-tab label="First"> 
                <as-split direction="horizontal">
                    <as-split-area size="50">
                        <mat-toolbar>
                            <span class="toolbar-heading">left</span>
                        </mat-toolbar>
                        <p> First </p>
                    </as-split-area>
                    <as-split-area size="50">
                        <p> Second </p>
                    </as-split-area>
                </as-split> 
   </mat-tab>
</mat-tab-group>
``` 

If i use it without the **MatTabModule** then its working. any solution to this ?

**Comment by bertrandg** [comment] 2018-11-25 17:30
Hi @Nexxado thanks for your pull request but I don't really like waiting time before calling `build()`, I've changed many things inside `2.x` version including working with css classes added/removed rather than setting style directly on DOM elements (https://github.com/bertrandg/angular-split/blob/2.0.0-preview/projects/angular-split/src/lib/component/split.component.scss).
It possibly solves the lazy loading issue, I need to reproduce it with old version to be sure it's solved with new one!

@dpatel44725 check this [stackblitz](https://stackblitz.com/edit/angular-t9kx5u?file=src%2Fapp%2Fapp.component.ts) using latest version `angular-split@2.0.0-beta.2` with material.
Please fork it to provide me an example showing your issue if you want help.

**Comment by sgulakmal** [comment] 2018-11-28 07:46
01. Use *ngIf and hide <as-split> (showContent = false)
02. Use timeout and true *ngIf Condition  (showContent = true)

*HTML file
 <as-split [direction]="'vertical'" [useTransition]="false" *ngIf="showContent">
    <as-split-area [size]="30">
      Test 01
    </as-split-area>
    <as-split-area [size]="70">
      Test 02
    </as-split-area>
</as-split>


*TS file
import {  OnInit, ChangeDetectorRef } from '@angular/core';
showContent = false;

constructor(private cd: ChangeDetectorRef) { }
  ngOnInit() {
    setTimeout(() => {
      this.showContent = true;
      this.cd.detectChanges();
    }, 300);
  }

**Comment by bertrandg** [comment] 2018-11-28 09:14
@sgulakmal What's you point??

**Comment by dpatel44725** [comment] 2018-11-28 18:42
> I have the same issue, but the only thing in my project is i am using this as-split inside **MatTabModule**
> 
> then it doesn't recognize the given size.
> 
> ```
> <mat-tab-group>
>   <mat-tab label="First"> 
>                 <as-split direction="horizontal">
>                     <as-split-area size="50">
>                         <mat-toolbar>
>                             <span class="toolbar-heading">left</span>
>                         </mat-toolbar>
>                         <p> First </p>
>                     </as-split-area>
>                     <as-split-area size="50">
>                         <p> Second </p>
>                     </as-split-area>
>                 </as-split> 
>    </mat-tab>
> </mat-tab-group>
> ```
> If i use it without the **MatTabModule** then its working. any solution to this ?

in this case if you use it with `<ng-template matTabContent>` then it will work. check the code below to get the idea.
```HTML
<mat-tab-group>
  <mat-tab label="First"> 
     <ng-template matTabContent>
           <as-split>(Your code goes here) </as-split>
      </ng-template>
  </mat-tab>
</mat-tab-group>
```

Thanks @bertrandg  for your reply.

**Comment by roukaour** [comment] 2018-11-28 18:44
@dpatel44725 Wrap the `<mat-tab>` content in `<ng-template matTabContent>`. This enables lazy loading for the tabs.

From [the Material Tabs documentation](https://material.angular.io/components/tabs/overview#lazy-loading): "Eagerly loaded tabs will initalize the child components but not inject them into the DOM until the tab is activated." Lazy loading prevents this, so when the tabs are both initialized and injected `AngularSplitModule` will be able to set their sizes.

**Comment by bertrandg** [comment] 2019-02-18 17:00
I've tested some scenario with a lazy loaded module and code from @sgulakmal ([stackblitz](https://stackblitz.com/edit/angular-4cnpkr?file=src%2Fapp%2Fapp.module.ts)) and it works well with current version `2.0.1` so I will close this issue for now.

Feel free to open another with stackblitz demo if you are still experimenting issue.

I'm gonna add a lazy loaded module demo to the website soon.

**Closed by bertrandg** 2019-02-18 17:00 UTC
