### ISSUE TITLE
split-area css width issue

### ISSUE THREAD

**Issue by Woden501** [bertrandg/angular-split#19] opened 2017-03-10 20:00 UTC
I've got a page with a split separating it into two columns.  The split-area for each column has a class "splitLeft" or "splitRight".  These classes specify minimum and maximum width values for each split-area which will allow the split to only travel within an acceptable range.  This is needed in my case in order to prevent sub columns in the right column from squashing together and becoming unusable.  When the split reaches one of the assigned maximums or minimums it will stop visually moving in the direction you are dragging; however, it appears that the width value continues to be increased as long as you continue dragging your mouse.  This means when you go to drag the split back the other direction you have to drag back the full amount you over-dragged previously plus what is visible on the screen.

If you have the maximum width set to 30px but don't release your mouse click until you've dragged to the 70px mark then the split will stop at 30px visually but the position of the split will be set at the 70px mark.  If you then try to drag from the 30px mark to the 20px mark you will actually have to drag 50px to the left before the split visually is at the 20px point.  Until you have dragged the 40px to make up the over-drag from 30px-70px earlier there will be no visual change to the split.

I have attempted to create a plunker to demonstrate the issue, but as this is the first time I've ever used plunker I'm not entirely sure this will work: https://plnkr.co/edit/2HllZ6zjhDKeC6EdrA96?p=preview

**Comment by bertrandg** [comment] 2017-03-13 20:56
Hi, your plunker works, I've experimented what you explain..

In fact, the behavior you are describing is not surprising. Even if you set a css `min-width` limit, javascript don't care and continue to calculate a new percentage depending a mouse position.

Currently, `angular-split` don't support minimum width split-area but I plan to add it in coming weeks due to several demands.

**Comment by aerlijman** [comment] 2017-05-10 20:09
Hi, I think I have the same problem. @bertrandg did you add support to have a min width and avoid the user to move more the drag indicator to below that limit?

**Comment by hem19** [comment] 2017-05-24 12:39
@bertrandg any updates on providing support for min/max height/width?

**Comment by kmmccafferty96** [comment] 2017-07-06 17:26
I think it would be great if this functionality was supported. Any updates?

**Comment by developernm** [comment] 2017-08-09 07:49
@bertrandg any updates for min-width?

**Comment by jraximus** [comment] 2017-09-05 21:30
@bertrandg I'm also looking for this and found your code. Are there any updates?

**Comment by bertrandg** [comment] 2017-11-14 09:59
duplicate of #4

**Closed by bertrandg** 2017-11-14 09:59 UTC
Labels: duplicate, enhancement
